[ca_server.conf]
listen_host=0.0.0.0
listen_port=8003
ca_db_path=data/ca.db
ca_cert_path=certs/ca_cert.pem
ca_private_key_path=certs/ca_key.pem
serial_counter=1
issued_cert_store=data/issued_certs
log_path=logs/ca.log.txt