[tgs_server.conf]
listen_host = 0.0.0.0
listen_port = 8001
tgs_db_path = tgs_db
tgs_id = TGS-001
service_id = CHATSERVER-001
ktgs_ref = key://ktgs/main
kv_ref = key://service/chatserver
ca_host = 172.27.29.34
ca_port = 8003
tgs_machine_id = TGS-HOST-001
identity_store_path = secure/tgs_identity
log_path = logs/tgs.log.txt